# Defaults for:
# - Hosts > Operating Systems
# - Hosts > Provisioning Templates
# - Hosts > Architectures
---

- name: CentOS Stream
  theforeman.foreman.operatingsystem:
    description: CentOS Stream
    family: Redhat
    name: CentOS
    major: '8'
    minor:
    release_name: stream
    password_hash: SHA256
    state: present
    architectures:
    - x86_64
    ptables:
    - Preseed default
    - Preseed default LVM
    media:
    - CentOS Stream
    provisioning_templates:
    - Preseed default
    - Preseed default finish
    - Preseed default PXELinux

- name: Preseed default finish
  theforeman.foreman.os_default_template:
    operatingsystem: CentOS Stream
    template_kind: finish
    provisioning_template: Preseed default finish
    state: present

- name: Preseed default
  theforeman.foreman.os_default_template:
    operatingsystem: CentOS Stream
    template_kind: provision
    provisioning_template: Preseed default
    state: present

- name: Preseed default PXELinux
  theforeman.foreman.os_default_template:
    operatingsystem: CentOS Stream
    template_kind: PXELinux
    provisioning_template: Preseed default PXELinux
    state: present
