# Defaults for:
# - Hosts > Operating Systems
# - Hosts > Provisioning Templates
# - Hosts > Architectures
---

- name: Ubuntu 22.04 LTS
  theforeman.foreman.operatingsystem:
    description: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
    family: Debian
    name: Ubuntu
    major: '22'
    minor: '04'
    release_name: jammy
    password_hash: SHA256
    state: present
    architectures:
    - x86_64
    ptables:
    - Preseed default
    - Preseed default LVM
    media:
    - Ubuntu mirror
    provisioning_templates:
    - Preseed default
    - Preseed default finish
    - Preseed default PXELinux

- name: Preseed default finish
  theforeman.foreman.os_default_template:
    operatingsystem: Ubuntu 22.04
    template_kind: finish
    provisioning_template: Preseed default finish
    state: present

- name: Preseed default
  theforeman.foreman.os_default_template:
    operatingsystem: Ubuntu 22.04
    template_kind: provision
    provisioning_template: Preseed default
    state: present

- name: Preseed default PXELinux
  theforeman.foreman.os_default_template:
    operatingsystem: Ubuntu 22.04
    template_kind: PXELinux
    provisioning_template: Preseed default PXELinux
    state: present
