#!/bin/sh

[ "$1" = "" ] && {
    echo "Download and customize docker-compose.yml from The Foreman project."
    echo
    echo "Usage: $0 <domain>"
    exit 1
}

wget -q -O- https://raw.githubusercontent.com/theforeman/foreman/develop/docker-compose.yml | \
sed -E \
    -e "s%^(version: .*)$%# The Foreman Docker Compose setup. Generated by:\n# $0\ $1\n\n\1%" \
    -e "s/example\.com/$1/g" \
    -e "/ build:/d" \
    -e "/ context: \./d" \
> docker-compose.yml
