#!/bin/sh -e
#
# Download and customize docker-compose.yml from The Foreman project.

[ "$1" = "" ] && {
    echo "Download and customize docker-compose.yml from The Foreman project."
    echo
    echo "Usage: $0 <domain>"
    exit 1
}

. $(dirname $0)/foreman-version.sh

wget -q -O- https://raw.githubusercontent.com/theforeman/foreman/develop/docker-compose.yml | \
sed -E \
    -e "s%^(version: .*)$%# The Foreman Docker Compose setup. Generated by:\n# $0\ $1\n\n\1%" \
    -e "s/ (image: .*):develop$/ \1:${FOREMAN_LATEST_STABLE}/g" \
    -e 's/- ".*:-127.0.0.1}:([0-9-]+:[0-9-]+)"$/- \1/' \
    -e "/ build:$/d" \
    -e "/   context: \.$/d" \
    -e "s/example\.com/$1/g" \
    -e "s|(start_period:.+$)|\1\n    volumes:\n      - tftpboot:/var/lib/tftpboot|" \
    -e "s|(^volumes:$)|  tftp:\n    image: wastrachan/tftpd\n    ports:\n      - 69:69/udp\n    volumes:\n      - tftpboot:/data\n\n\1|" \
    -e "s|(redis-persistent:$)|\1\n  tftpboot:|" \
\
> $(dirname $0)/../docker-compose.yml
