# Defaults for:
# - Configure > Host Groups
---

- name: Hostgroup laptops
  theforeman.foreman.hostgroup:
    name: laptops
    description: Portable workstations
    domain: local
    architecture: x86_64
    operatingsystem: Ubuntu 22.04
    medium: Ubuntu mirror
    ptable: Preseed default
    pxe_loader: PXELinux BIOS
    organizations:
    - My family
    locations:
    - Home, sweet home
    state: present
